"""New Migration

Revision ID: 232dcfa13eb5
Revises: 471b6fff6cee
Create Date: 2023-06-09 17:56:00.330339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232dcfa13eb5'
down_revision = '471b6fff6cee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy', sa.Column('series_id', sa.Integer(), nullable=True))
    op.add_column('dummy', sa.Column('match_id', sa.Integer(), nullable=True))
    op.add_column('dummy', sa.Column('ball_id', sa.Integer(), nullable=False))
    op.drop_index('ix_dummy_ballid', table_name='dummy')
    op.create_index(op.f('ix_dummy_ball_id'), 'dummy', ['ball_id'], unique=False)
    op.drop_column('dummy', 'id')
    op.drop_column('dummy', 'seriesid')
    op.drop_column('dummy', 'ballid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummy', sa.Column('ballid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('dummy', sa.Column('seriesid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dummy', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dummy_ball_id'), table_name='dummy')
    op.create_index('ix_dummy_ballid', 'dummy', ['ballid'], unique=False)
    op.drop_column('dummy', 'ball_id')
    op.drop_column('dummy', 'match_id')
    op.drop_column('dummy', 'series_id')
    # ### end Alembic commands ###
