"""new

Revision ID: 471b6fff6cee
Revises: 
Create Date: 2023-06-09 11:17:06.783448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471b6fff6cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('ballid', sa.Integer(), nullable=False),
    sa.Column('seriesid', sa.Integer(), nullable=True),
    sa.Column('inningNumber', sa.Integer(), nullable=True),
    sa.Column('oversActual', sa.Float(), nullable=True),
    sa.Column('overNumber', sa.Integer(), nullable=True),
    sa.Column('ballNumber', sa.Integer(), nullable=True),
    sa.Column('totalRuns', sa.Integer(), nullable=True),
    sa.Column('batsman', sa.String(), nullable=True),
    sa.Column('bowler', sa.String(), nullable=True),
    sa.Column('batsmanRuns', sa.Integer(), nullable=True),
    sa.Column('isFour', sa.Integer(), nullable=True),
    sa.Column('isSix', sa.Integer(), nullable=True),
    sa.Column('isWicket', sa.Integer(), nullable=True),
    sa.Column('dismissalType', sa.Float(), nullable=True),
    sa.Column('byes', sa.Integer(), nullable=True),
    sa.Column('legbyes', sa.Integer(), nullable=True),
    sa.Column('wides', sa.Integer(), nullable=True),
    sa.Column('noballs', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ballid')
    )
    op.create_index(op.f('ix_dummy_ballid'), 'dummy', ['ballid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dummy_ballid'), table_name='dummy')
    op.drop_table('dummy')
    # ### end Alembic commands ###
